import { t, getLanguage } from './i18n';
import { useEffect, useState } from 'react';
import { useCalendarKind, formatDate, type CalendarKind } from './calendar';

const iso = (date: Date) => date.toISOString().slice(0, 10);
const dateOf = (value: string) => new Date(`${value}T12:00:00`);
const locale = (kind: CalendarKind) => `${getLanguage()}-u-ca-${kind === 'gregorian' ? 'gregory' : kind}-nu-latn`;
type Parts = { year: string; month: string; day: string };
function parts(date: Date, kind: CalendarKind): Parts { const found = new Intl.DateTimeFormat(locale(kind), { year: 'numeric', month: 'numeric', day: 'numeric' }).formatToParts(date); return Object.fromEntries(found.filter(x => x.type !== 'literal').map(x => [x.type, x.value])) as Parts }
function sameMonth(a: Parts, b: Parts) { return a.year === b.year && a.month === b.month }
function monthStart(anchor: Date, kind: CalendarKind) { const target = parts(anchor, kind); for (let offset = 0; offset < 370; offset++) { const candidate = new Date(anchor); candidate.setDate(candidate.getDate() - offset); const p = parts(candidate, kind); if (sameMonth(p, target) && Number(p.day) === 1) return candidate } return anchor }
function nextMonth(start: Date, kind: CalendarKind, direction: 1 | -1) { const current = parts(start, kind); for (let offset = 1; offset < 370; offset++) { const candidate = new Date(start); candidate.setDate(candidate.getDate() + offset * direction); const p = parts(candidate, kind); if (Number(p.day) === 1 && !sameMonth(p, current)) return direction === 1 ? candidate : monthStart(candidate, kind) } return start }
function findMonth(year: number, month: number, kind: CalendarKind, anchor: Date) {
    if (kind === 'gregorian') return new Date(year, month - 1, 1, 12);
    const current = parts(anchor, kind); const estimate = new Date(anchor); const distance = (year - Number(current.year)) * 12 + (month - Number(current.month)); estimate.setDate(estimate.getDate() + Math.round(distance * 30.44));
    for (let offset = 0; offset < 400; offset++)for (const direction of offset ? [1, -1] : [1]) { const candidate = new Date(estimate); candidate.setDate(candidate.getDate() + offset * direction); const p = parts(candidate, kind); if (Number(p.year) === year && Number(p.month) === month && Number(p.day) === 1) return candidate }
    return monthStart(anchor, kind);
}
function monthName(year: number, month: number, kind: CalendarKind, anchor: Date) { return new Intl.DateTimeFormat(locale(kind), { month: 'long' }).format(findMonth(year, month, kind, anchor)) }

export function LocalizedDateInput({ value, onChange, max }: { value: string; onChange: (value: string) => void; max?: string }) {
    const kind = useCalendarKind(); const maxDate = max ? dateOf(max) : null; const initialDate = value ? dateOf(value) : new Date(); const [open, setOpen] = useState(false), [cursor, setCursor] = useState(() => maxDate && initialDate > maxDate ? maxDate : initialDate);
    useEffect(() => { if (value) { const next = dateOf(value); setCursor(maxDate && next > maxDate ? maxDate : next) } }, [value, max]);
    const start = monthStart(cursor, kind); const currentParts = parts(start, kind); const selectedYear = Number(currentParts.year), selectedMonth = Number(currentParts.month); const todayParts = parts(new Date(), kind); const minYear = Math.min(selectedYear, Number(todayParts.year) - 120), maxYear = maxDate ? Number(parts(maxDate, kind).year) : Math.max(selectedYear, Number(todayParts.year) + 20); const years = Array.from({ length: maxYear - minYear + 1 }, (_, index) => maxYear - index); const months = Array.from({ length: 12 }, (_, index) => index + 1);
    const firstDay = kind === 'gregorian' ? 0 : 6; const padding = (start.getDay() - firstDay + 7) % 7; const days: Array<Date | null> = Array(padding).fill(null); for (let offset = 0; offset < 42 - padding; offset++) { const candidate = new Date(start); candidate.setDate(candidate.getDate() + offset); if (!sameMonth(parts(candidate, kind), parts(start, kind))) break; days.push(candidate) }
    const weekdays = Array.from({ length: 7 }, (_, i) => new Intl.DateTimeFormat(getLanguage(), { weekday: 'short' }).format(new Date(2024, 0, 7 + (firstDay + i) % 7)));
    const followingMonth = nextMonth(start, kind, 1), canGoNext = !maxDate || followingMonth <= maxDate;
    return <div className="localized-date"><button type="button" className="localized-date-value" onClick={() => setOpen(x => !x)} aria-haspopup="dialog">{value ? formatDate(value, kind) : t('انتخاب تاریخ')}</button>{open && <div className="date-popover" role="dialog" aria-label={t('انتخاب تاریخ')}><div className="date-nav"><button type="button" aria-label={t('Previous month')} onClick={() => setCursor(nextMonth(start, kind, -1))}>‹</button><div className="date-jump"><select className="date-month-select" aria-label={t('Month')} value={selectedMonth} onChange={event => { const next = findMonth(selectedYear, Number(event.target.value), kind, start); setCursor(maxDate && next > maxDate ? maxDate : next) }}>{months.map(month => <option value={month} key={month}>{monthName(selectedYear, month, kind, start)}</option>)}</select><select className="date-year-select" aria-label={t('Year')} value={selectedYear} onChange={event => { const next = findMonth(Number(event.target.value), selectedMonth, kind, start); setCursor(maxDate && next > maxDate ? maxDate : next) }}>{years.map(year => <option value={year} key={year}>{year}</option>)}</select></div><button type="button" aria-label={t('Next month')} disabled={!canGoNext} onClick={() => canGoNext && setCursor(followingMonth)}>›</button></div><div className="date-grid">{weekdays.map((x, index) => <span className="date-weekday" key={index}>{x}</span>)}{days.map((date, index) => date ? <button type="button" key={iso(date)} className={value === iso(date) ? 'selected' : ''} disabled={Boolean(maxDate && date > maxDate)} onClick={() => { onChange(iso(date)); setOpen(false) }}>{parts(date, kind).day}</button> : <span key={`blank-${index}`} />)}</div></div>}</div>
}
