import { t } from './i18n';
import { useEffect, useState } from 'react';
import { getLanguage, languageChanged, type Locale } from './i18n';
import { calendarChanged, getCalendarKind, type CalendarKind } from './calendar';
import { LegalPanel } from './legal';
import { getMeasurementUnits, saveMeasurementUnits, type HeightUnit, type WeightUnit } from './units';

export const settingsOpen = 'health-settings-open';

export function SettingsPanel() {
    const initialUnits = getMeasurementUnits(); const [open, setOpen] = useState(false); const [legal, setLegal] = useState(false); const [language, setLanguage] = useState<Locale>(getLanguage); const [calendar, setCalendar] = useState<CalendarKind>(getCalendarKind); const [heightUnit, setHeightUnit] = useState<HeightUnit>(initialUnits.height); const [weightUnit, setWeightUnit] = useState<WeightUnit>(initialUnits.weight);
    const openInTab = () => chrome.tabs.create({ url: chrome.runtime.getURL('index.html') });
    const show = () => { const units = getMeasurementUnits(); setLanguage(getLanguage()); setCalendar(getCalendarKind()); setHeightUnit(units.height); setWeightUnit(units.weight); setOpen(true) };
    useEffect(() => { const openFromMenu = () => show(); window.addEventListener(settingsOpen, openFromMenu); return () => window.removeEventListener(settingsOpen, openFromMenu) }, []);
    useEffect(() => { const sync = () => setLanguage(getLanguage()); window.addEventListener(languageChanged, sync); return () => window.removeEventListener(languageChanged, sync) }, []);
    const save = () => { localStorage.setItem('health-language', language); localStorage.setItem('health-calendar', calendar); saveMeasurementUnits({ height: heightUnit, weight: weightUnit }); window.dispatchEvent(new Event(languageChanged)); window.dispatchEvent(new Event(calendarChanged)); setOpen(false) };
    return <><button className="settings-trigger" onClick={show} aria-label={t('Settings')}>⚙</button><button className="open-tab-trigger" onClick={openInTab} aria-label={t('Open in new tab')} title={t('Open in new tab')}>↗</button>{open && <div className="modal settings-modal"><div className="settings-content"><button className="modal-close" onClick={() => setOpen(false)} aria-label={t('Close')}>×</button><h2>{t('تنظیمات')}</h2><p>{t('نمایش زبان و تقویم را فقط برای همین دستگاه انتخاب کنید.')}</p><section><h3>{t('نمایش')}</h3><button className="open-tab" onClick={openInTab}>{t('Open in new tab')}</button></section><section><h3>{t('زبان رابط')}</h3><select value={language} onChange={e => setLanguage(e.target.value as Locale)}><option value="en">English</option><option value="fa">فارسی</option><option value="ar">العربية</option><option value="he">עברית</option><option value="fr">Français</option><option value="it">Italiano</option><option value="es">Español</option><option value="tr">Türkçe</option></select></section><section><h3>{t('تقویم')}</h3><select value={calendar} onChange={e => setCalendar(e.target.value as CalendarKind)}><option value="gregorian">{t('میلادی')}</option><option value="persian">{t('هجری شمسی')}</option><option value="islamic">{t('قمری')}</option></select></section><section><h3>{t('Measurement units')}</h3><div className="unit-settings"><label>{t('Height unit')}<select value={heightUnit} onChange={e => setHeightUnit(e.target.value as HeightUnit)}><option value="cm">cm</option><option value="ft">ft</option></select></label><label>{t('Weight unit')}<select value={weightUnit} onChange={e => setWeightUnit(e.target.value as WeightUnit)}><option value="kg">kg</option><option value="lb">lb</option></select></label></div></section><section><h3>{t('حریم خصوصی')}</h3><button className="open-tab" onClick={() => setLegal(true)}>{t('حریم خصوصی و قوانین استفاده')}</button></section><footer><button className="primary" onClick={save}>{t('ذخیره')}</button></footer></div></div>}{legal && <LegalPanel close={() => setLegal(false)} />}</>;
}
